# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github_app:
    client_id: <%= ENV["GITHUB_APP_CLIENT_ID"] %>
    client_secret: <%= ENV["GITHUB_APP_CLIENT_KEY"] %>

development:
  <<: *default
  secret_key_base: 45b3776bf705db0415298401f965de1565fd40de57b8ea61f1d49daf28befbfaeabf663ea1923db4c686d77208d7fc4133df44eb424a5d502123155a40033258

test:
  <<: *default
  secret_key_base: 91e7e0a8329c43a724395b72ddc05924e8a4b588082aa85d5f2d3beebac99f2d0aff28af21be5a72e7ed5c9e0d34401119ef4b22de6a727150f7365a08bee964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
